# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caee240a8290a465d69835aaa6ea139bd36d7945591178aae06ab8169673b38cfc8d427441be9635613e324b9e5796c7467515949718ac2f876faed3b3a41236

test:
  secret_key_base: 4ceaa8e8ec0941a24bd4787e758a7873f7db0a64205cec9720d33d6a46fafb275ab3cd58496546428b969c9ccf3a766335595857d65894ffaee3a92987dece7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
